export const loginStyles = {
  pageWrapper: {
    minHeight: '100vh',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    background: 'linear-gradient(180deg, #F5F3FF 0%, #EDE9FE 100%)',
    px: 2,
  },
  card: { width: '100%', maxWidth: 360, p: 4 },
  subheading: { mb: 3 },
  fieldLabel: { fontWeight: 600 },
  field: { mt: 0.5, mb: 2 },
  passwordField: { mt: 0.5, mb: 1 },
  inputAdornmentIcon: { color: 'text.secondary' },
  rememberRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    mb: 2,
  },
  signInButton: {
    py: 1.2,
    borderRadius: 2,
    textTransform: 'none',
    fontWeight: 600,
  },
  divider: { my: 3 },
  // socialButtonsRow: { display: 'flex', gap: 2 },
  // socialButton: { textTransform: 'none', borderRadius: 2 },
};