export const signupStyles = {
  pageWrapper: {
    minHeight: '100vh',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    background: 'linear-gradient(180deg, #F5F3FF 0%, #EDE9FE 100%)',
    px: 2,
    py: 4,
  },
  card: { width: '100%', maxWidth: 380, p: 4 },
  logo: { mb: 2 },
  heading: {},
  subheading: { mb: 3 },
  fieldLabel: { fontWeight: 600 },
  field: { mt: 0.5, mb: 2 },
  passwordField: { mt: 0.5, mb: 1 },
  passwordHint: { display: 'block', mb: 3 },
  inputAdornmentIcon: { color: 'text.secondary' },
  createButton: { py: 1.2, borderRadius: 2, textTransform: 'none', fontWeight: 600 },
  divider: { my: 3 },
  dividerTight: { my: 2 },
  socialButtonsRow: { display: 'flex', gap: 2, mb: 3 },
  socialButton: { textTransform: 'none', borderRadius: 2 },
  footerText: { display: 'block' },
};